### ISSUE TITLE
Survival analysis

### ISSUE THREAD

**Issue by ellispatrick** [SydneyBioX/spicyR#18]
It would be great if spicyR could work on a survival outcome.

**Comment by fame2827** [comment]
Added survival support: https://github.com/SydneyBioX/spicyR/commit/25c12bac3463aed45b5b7dc99a426d3a8d298bc4 and support for mixed effects survival modelling: https://github.com/SydneyBioX/spicyR/commit/e1fd66f9e6d9ec16a9619c67dd795153688111e1
