### ISSUE TITLE
topPairs signif figures

### ISSUE THREAD

**Issue by ellispatrick** [SydneyBioX/spicyR#27]
topPairs output is ugly, reduce the number of significant figures.

**Comment by nick-robo** [comment]
Do we want to actually round the numbers? What if the values need to be adjusted or used downstream? Unless we actually change the values, the issue is with the `data.frame` show method.

**Comment by ellispatrick** [comment]
You're right I guess. Maybe we need a showTopPairs() function? or we can add signif as an argument? Regardless, not urgent.
