### ISSUE TITLE
groups in spicy comparison

### ISSUE THREAD

**Issue by SchulzDan** [SydneyBioX/spicyR#29]
Hi Ellis,

been using the spicy function a few times and like it. One thing that confuses me is that I am always unsure which comparison is group A and group B (e.g. in the signifPlot). I see that I can call the object (result of the function) and then in my particular case now it says:
"Number of differentially localised cell type pairs: 
conditionlow_low_density
58"
also in the other tables of the object that is the condition that is listed so assuming that it is group B?

Thanks for clarifying.

Daniel

**Comment by nick-robo** [comment]
We have added a variable to `signifPlot` to specify the comparison group (`comparisonGroup`). Now the plot will also show the correct labels in the condition legend.
