### ISSUE TITLE
Identify images with high attraction/avoidance for certain celltype combinations

### ISSUE THREAD

**Issue by StefanosVoglis** [SydneyBioX/spicyR#30]
Hi,
super nice package!

I am trying to identify images with very high attraction / avoidance of certain celltype combinations to illustrate the findings of the signifPlot with some spatial illustrations. Is it suitable to use the pairwiseAssoc values from the spicy test object? And what do they exactly mean? Positive values = attraction / negative values = avoidance? 

Thanks in advance and for your great work,

Stefanos

**Comment by alexrunqin** [comment]
Hi Stefanos! 

You can definitely use the `pairwiseAssoc` values from the spicy test object (`spicyTest$pairwiseAssoc`). These would be the raw outputs of the L function for distance between 2 cell types for each unique image.

And yep, positive values = attraction, and negative values = avoidance. You can essentially interpret this as the bigger the number, the greater the amount of attraction/avoidance.

Hope that helps!
Alex

**Comment by nick-robo** [comment]
Please reopen if you have further questions.
