### ISSUE TITLE
Add G function

### ISSUE THREAD

**Issue by ellispatrick** [SydneyBioX/spicyR#6]
Are there other spatial stats we should add?

**Comment by celsomilne** [comment]
- [ ] `Fest`

- [ ] `Gest`

- [ ] `Jest`

- [ ] `Kest`

And the dot version of all those functions too. It may be easier to implement an `as.ppp.SegmentedCells` function to easily wrap all `spatstat` functions, or we could return a list of `ppp` objects, split by `imageID`. What are your thoughts?

**Comment by ellispatrick** [comment]
Too hard basket
